services:
  backend:
    build: .
    container_name: django_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: auth_db
      DB_USER: auth_user
      DB_PASSWORD: 'Kumar123#'
      DB_HOST: db
      DB_PORT: 5432
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: 'Kumar123#'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
